version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 20
  assignees:
    - "theradcolor"
  reviewers:
    - "theradcolor"
